Repository CryptoScamDB/api.cryptoscamdb.org, pull requests merged in 2018-11, with the labels that each got.

#4 Provides price/check/report endpoints for eth/etc/btc/bch/ltc
  package-lock.json
  package.json
  src/app.ts
  src/models/coins.ts
  src/models/configcoin.ts
  src/models/entry.ts
  src/models/entrywrapper.ts
  src/scripts/update.ts
  src/utils/addressCheck.ts
  src/utils/apiKeyTest.ts
  src/utils/autoPR.ts
  src/utils/categorize.ts
  src/utils/classes/github.class.js
  src/utils/config.ts
  src/utils/db.ts
  src/utils/ensResolve.ts
  src/utils/gcaptcha.ts
  src/utils/lookup.ts
  src/utils/router.ts
  src/utils/slack.ts
  tests/testautopr.ts
  tests/testensresolve.ts
  tsconfig.json
Labels: wip

#23 Api gateway fix
  src/app.ts
  src/utils/apiKeyTest.ts
  src/utils/autoPR.ts
  src/utils/config.ts
  src/utils/db.ts
  src/utils/lookup.ts
  src/utils/router.ts
Labels: size/L, size/M

#25 Version 0.2.0
  package-lock.json
  package.json
Labels: size/XS

#26 Added functionality to expand the /stats endpoint
  src/utils/db.ts
  src/utils/router.ts
Labels: size/M

#24 Make coin symbols uppercase
  src/models/configcoin.ts
  src/utils/autoPR.ts
  src/utils/balanceLookup.ts
  src/utils/config.ts
  src/utils/db.ts
  src/utils/endpoints.ts
  src/utils/ensResolve.ts
  src/utils/router.ts
  src/utils/writeConfig.ts
Labels: size/L

#28 Pin exact version of dependencies
  package-lock.json
  package.json
Labels: size/XL
