Repository CryptoScamDB/api.cryptoscamdb.org, pull requests merged in 2019-02, with the labels that each got.

#31 [WIP] Sqlite implementation
  .gitignore
  examples/ens.ts
  examples/pr.ts
  examples/regex.ts
  nodemon.json
  package-lock.json
  package.json
  src/app.ts
  src/classes/github.class.ts
  src/classes/repo.class.ts
  src/classes/scam.class.ts
  src/routes/fallback.ts
  src/routes/index.ts
  src/routes/update.ts
  src/routes/v1/abusereport.ts
  src/routes/v1/actives.ts
  src/routes/v1/addresses.ts
  src/routes/v1/balance.ts
  src/routes/v1/blacklist.ts
  src/routes/v1/check.ts
  src/routes/v1/coininfo.ts
  src/routes/v1/domain.ts
  src/routes/v1/domainslist.ts
  src/routes/v1/entry.ts
  src/routes/v1/featured.ts
  src/routes/v1/inactives.ts
  src/routes/v1/ips.ts
  src/routes/v1/postReport.ts
  src/routes/v1/price.ts
  src/routes/v1/putReport.ts
  src/routes/v1/reportedlist.ts
  src/routes/v1/scams.ts
  src/routes/v1/stats.ts
  src/routes/v1/verified.ts
  src/routes/v1/whitelist.ts
  src/scripts/update.ts
  src/utils/addressCheck.ts
  src/utils/autoPR.ts
  src/utils/db.ts
  src/utils/ensResolve.ts
  src/utils/getID.ts
  src/utils/github.ts
  src/utils/router.ts
  src/utils/testCoinType.ts
  tests/ens.ts
  tests/regex.ts
  tests/testensresolve.ts
  tsconfig.json
  tslint.json
Labels: enhancement, size/XL, wip

#56 Update ENS endpoint
  src/utils/ensResolve.ts
Labels: size/XS

#55 Fix lookup case-sensitivity bug
  src/routes/v1/domain.ts
Labels: size/XS

#46 Fix report process errors
  src/classes/repo.class.ts
  src/routes/v1/scams.ts
  src/utils/autoPR.ts
  src/utils/db.ts
  tests/ens.ts
  tests/regex.ts
  tslint.json
Labels: size/L, wip
